### ISSUE TITLE
Fix Client Info tests

### ISSUE THREAD

**Issue by leenlab2** [TLI-group3/TLI-client#25]
For some reason, I cannot get the tests in client info to wait until the cars have been fetched. debugging showed me that it is calling the /cars endpoint, but the response is empty. I have no idea what, why, how, or when. 

My best guess is that this might be related to how slow the response can be from /cars. Either figure out how to make it wait, or use a mock endpoint to return the cars.

**Comment by Infinityworld13** [comment]
Tests were deleted due to time constrains and difficulty with async functions
